### ISSUE TITLE
SInts not respected in Legalize for connection where rhs is wider SInt than lhs

### ISSUE THREAD

**Issue by jackkoenig** [ucb-bar/firrtl#173]
Similarl to #169
```
 circuit Test :
  module Test :
    input b : SInt<32>
    output x : SInt<16>
    skip
    x <= b
```
->
```
 circuit Test :
  module Test :
    input b : SInt<32>
    output x : SInt<16>
    skip
    x <= bits(b, 15, 0)
```

**Comment by jackkoenig** [comment]
Fix coming for this as well

**Comment by jackkoenig** [comment]
Per my proposed fix, according to the spec assignment of wider ground types to narrower ground types is not even allowed. Is this changing @azidar or do we need to fix the compiler?

**Comment by azidar** [comment]
Yeah, so first we should change Chisel3 to always emit partial connects, and then we can check for this in checkwidths

**Comment by aswaterman** [comment]
I tried, but started to get match errors in Remove CHIRRTL:

    Exception in thread "main" scala.MatchError: (UIntType(IntWidth(1)),UnknownType()) (of class scala.Tuple2)
      at firrtl.Utils$.get_valid_points(Utils.scala:311)
      at firrtl.passes.RemoveCHIRRTL$.firrtl$passes$RemoveCHIRRTL$$remove_chirrtl_s$1(Passes.scala:1397)
      at firrtl.passes.RemoveCHIRRTL$$anonfun$firrtl$passes$RemoveCHIRRTL$$remove_chirrtl_s$1$3.apply(Passes.scala:1411)

**Comment by aswaterman** [comment]
The chisel3 branch is here: https://github.com/ucb-bar/chisel3/tree/partial-connect
