### ISSUE TITLE
Error in BulkEquals using FixTypes

### ISSUE THREAD

**Issue by chick** [ucb-bar/firrtl#241]
```
(FixedType(IntWidth(6),IntWidth(4)),FixedType(IntWidth(6),IntWidth(4))) (of class scala.Tuple2)
scala.MatchError: (FixedType(IntWidth(6),IntWidth(4)),FixedType(IntWidth(6),IntWidth(4))) (of class scala.Tuple2)
	at firrtl.passes.CheckTypes$.firrtl$passes$CheckTypes$$bulk_equals$1(Checks.scala:487)
	at firrtl.passes.CheckTypes$$anonfun$firrtl$passes$CheckTypes$$bulk_equals$1$1$$anonfun$apply$mcVI$sp$1.apply$mcVI$sp(Checks.scala:498)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at firrtl.passes.CheckTypes$$anonfun$firrtl$passes$CheckTypes$$bulk_equals$1$1.apply$mcVI$sp(Checks.scala:494)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at firrtl.passes.CheckTypes$.firrtl$passes$CheckTypes$$bulk_equals$1(Checks.scala:493)
	at firrtl.passes.CheckTypes$.firrtl$passes$CheckTypes$$check_types_s$1(Checks.scala:513)
	at firrtl.passes.CheckTypes$$anonfun$firrtl$passes$CheckTypes$$check_types_s$1$2.apply(Checks.scala:529)
	at firrtl.passes.CheckTypes$$anonfun$firrtl$passes$CheckTypes$$check_types_s$1$2.apply(Checks.scala:529)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at firrtl.Mappers$StmtMagnet$$anon$4.map(Mappers.scala:44)
	at firrtl.Mappers$StmtMap.map(Mappers.scala:95)
	at firrtl.passes.CheckTypes$.firrtl$passes$CheckTypes$$check_types_s$1(Checks.scala:529)
	at firrtl.passes.CheckTypes$$anonfun$run$2.apply(Checks.scala:536)
	at firrtl.passes.CheckTypes$$anonfun$run$2.apply(Checks.scala:532)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at firrtl.passes.CheckTypes$.run(Checks.scala:532)
	at firrtl.SimpleRun$$anonfun$1$$anonfun$2.apply(LoweringCompilers.scala:48)
	at firrtl.SimpleRun$$anonfun$1$$anonfun$2.apply(LoweringCompilers.scala:48)
	at firrtl.Utils$.time(Utils.scala:57)
	at firrtl.SimpleRun$$anonfun$1.apply(LoweringCompilers.scala:48)
	at firrtl.SimpleRun$$anonfun$1.apply(LoweringCompilers.scala:46)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at firrtl.SimpleRun$class.run(LoweringCompilers.scala:45)
	at firrtl.ResolveAndCheck.run(LoweringCompilers.scala:83)
	at firrtl.ResolveAndCheck.execute(LoweringCompilers.scala:97)
	at firrtl.Compiler$$anonfun$compile$1.apply(Compiler.scala:71)
	at firrtl.Compiler$$anonfun$compile$1.apply(Compiler.scala:70)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at firrtl.Compiler$class.compile(Compiler.scala:70)
	at firrtl.LowFirrtlCompiler.compile(LoweringCompilers.scala:185)
	at firrtl_interpreter.ToLoFirrtl$.lower(ToLoFirrtl.scala:15)
	at firrtl_interpreter.FirrtlTerp.<init>(FirrtlTerp.scala:34)
	at firrtl_interpreter.FirrtlTerp$.apply(FirrtlTerp.scala:152)
	at firrtl_interpreter.InterpretiveTester.<init>(InterpretiveTester.scala:20)
	at chisel3.iotesters.FirrtlTerpBackend.<init>(FirrtlTerpBackend.scala:20)
	at chisel3.iotesters.setupFirrtlTerpBackend$.apply(FirrtlTerpBackend.scala:97)
	at chisel3.iotesters.Driver$.apply(Driver.scala:22)
	at examples.SimpleOneArgBundleSpec$$anonfun$2.apply$mcV$sp(OneArgSpec.scala:57)
	at examples.SimpleOneArgBundleSpec$$anonfun$2.apply(OneArgSpec.scala:59)
	at examples.SimpleOneArgBundleSpec$$anonfun$2.apply(OneArgSpec.scala:59)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

**Comment by azidar** [comment]
Hopefully that fixes your issue! :)
