### ISSUE TITLE
FixedPoint circuit pass error

### ISSUE THREAD

**Issue by chick** [ucb-bar/firrtl#259]
This circuit
```
circuit ParameterizedNumberOperation : 
  module ParameterizedNumberOperation : 
    input clk : Clock
    input reset : UInt<1>
    output io : {flip a1 : Fixed<16><<8>>, flip a2 : Fixed<16><<8>>, c : Fixed<48><<8>>}
    
    io is invalid
    reg register1 : Fixed<48><<8>>, clk
    node T_10 = mul(io.a1, io.a2) @[FixedPointRing.scala 23:7] 
    register1 <= T_10 @[ParameterizedOpSpec.scala 27:13] 
    io.c <= register1 @[ParameterizedOpSpec.scala 37:8] 
```
Causes the following firrtl error.  It happens for a number of different widths of register1
```
Shouldn't be here
java.lang.RuntimeException: Shouldn't be here
	at scala.sys.package$.error(package.scala:27)
	at scala.Predef$.error(Predef.scala:139)
	at firrtl.passes.ConvertFixedToSInt$.alignArg(ConvertFixedToSInt.scala:19)
	at firrtl.passes.ConvertFixedToSInt$.firrtl$passes$ConvertFixedToSInt$$updateStmtType$1(ConvertFixedToSInt.scala:85)
	at firrtl.passes.ConvertFixedToSInt$$anonfun$firrtl$passes$ConvertFixedToSInt$$updateStmtType$1$7.apply(ConvertFixedToSInt.scala:92)
	at firrtl.passes.ConvertFixedToSInt$$anonfun$firrtl$passes$ConvertFixedToSInt$$updateStmtType$1$7.apply(ConvertFixedToSInt.scala:92)
```

**Comment by chick** [comment]
Did a pull and this behavior is not happening now
