### ISSUE TITLE
Bug in CHIRRTL mem handling

### ISSUE THREAD

**Issue by aswaterman** [ucb-bar/firrtl#325]
The following bails out in RemoveCHIRRTL's collect_smems_and_mports:

```
circuit Queue :
  module Queue :
    input clock : Clock

    cmem ram : UInt<1>[2]
    infer mport T_107 = ram[UInt(0)], clock
```

The issue seems to be that an "infer" port is declared that isn't actually used.  The right behavior should be to disregard the port.  Here is a stack trace:

```
Exception in thread "main" scala.MatchError: MInfer (of class firrtl.MInfer$)
  at firrtl.passes.RemoveCHIRRTL$.collect_smems_and_mports(RemoveCHIRRTL.scala:76)
  at firrtl.passes.RemoveCHIRRTL$$anonfun$collect_smems_and_mports$1.apply(RemoveCHIRRTL.scala:84)
  at firrtl.passes.RemoveCHIRRTL$$anonfun$collect_smems_and_mports$1.apply(RemoveCHIRRTL.scala:84)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at firrtl.ir.Block.mapStmt(IR.scala:227)
  at firrtl.Mappers$StmtMagnet$$anon$1.map(Mappers.scala:41)
  at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:55)
  at firrtl.passes.RemoveCHIRRTL$.collect_smems_and_mports(RemoveCHIRRTL.scala:84)
  at firrtl.passes.RemoveCHIRRTL$$anonfun$remove_chirrtl_m$1.apply(RemoveCHIRRTL.scala:247)
  at firrtl.passes.RemoveCHIRRTL$$anonfun$remove_chirrtl_m$1.apply(RemoveCHIRRTL.scala:247)
  at firrtl.ir.Module.mapStmt(IR.scala:443)
  at firrtl.Mappers$ModuleMagnet$$anon$11.map(Mappers.scala:115)
  at firrtl.Mappers$ModuleMap$.map$extension(Mappers.scala:125)
  at firrtl.passes.RemoveCHIRRTL$.remove_chirrtl_m(RemoveCHIRRTL.scala:247)
  at firrtl.passes.RemoveCHIRRTL$$anonfun$10.apply(RemoveCHIRRTL.scala:253)
  at firrtl.passes.RemoveCHIRRTL$$anonfun$10.apply(RemoveCHIRRTL.scala:253)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at firrtl.passes.RemoveCHIRRTL$.run(RemoveCHIRRTL.scala:253)
```

**Comment by aswaterman** [comment]
I suspect what's going on is that the MInfer isn't being transformed because it isn't read from or written to.  This cropped up because of a chisel3/gsdt bug, which for a yet-to-be-determined reason didn't emit code to read from the cmem in the Queue.
